'WELLNESS': 0
'POLITICS': 1
'PARENTS': 2
'WORLDPOST': 3
'HOME & LIVING': 4
'HEALTHY LIVING': 5
'QUEER VOICES': 6
'STYLE & BEAUTY': 7
'WEDDINGS' : 8
'IMPACT' : 9
'FOOD & DRINK': 10
'COMEDY' : 11
'PARENTING': 12
'ENTERTAINMENT': 13
'ENVIRONMENT': 14
'WORLD NEWS': 15
'COLLEGE': 16
'TECH': 17
'DIVORCE': 18
'RELIGION': 19
'THE WORLDPOST': 20
'WOMEN': 21
'MONEY': 22
'ARTS & CULTURE': 23
'BLACK VOICES': 24
'TRAVEL': 25
'GOOD NEWS': 26
'SCIENCE': 27
'BUSINESS': 28
'ARTS': 29
'SPORTS': 30
'WEIRD NEWS': 31
'MEDIA': 32
'CRIME': 33
'EDUCATION': 34
'LATINO VOICES': 35
'TASTE': 36
'GREEN': 37
'STYLE': 38
'U.S. NEWS': 39
'CULTURE & ARTS': 40
'FIFTY': 41
'unknown': 99
